# 1.8 Lineal Albebra Refresher

## Vector Operations

In [6]:
import numpy as np

In [9]:
u = np.array([2,4,5,6])
v = np.array([1, 0, 0 , 2])

In [8]:
2 * u 

array([ 4,  8, 10, 12])

In [10]:
u + v

array([3, 4, 5, 8])

## Multiplication 

## Multiplication 

### Vector - vector multiplication (dot product)

In [15]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0] 
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [16]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [17]:
u.dot(v)

np.int64(14)

### Matrix Vector Multiplication 

In [21]:
m = np.array([[2,4,5,6],
 [1,2,1,2],
 [3,1,2,1]])

m * u

array([[ 4, 16, 25, 36],
       [ 2,  8,  5, 12],
       [ 6,  4, 10,  6]])

In [25]:
def matrix_vector_multiplication(m,v):
    assert m.shape[1] == v.shape[0]

    num_rows = m.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(m[i],v)
        
    return result

In [26]:
matrix_vector_multiplication(m,v)

array([14.,  5.,  5.])

In [27]:
m.dot(v)

array([14,  5,  5])

## Matrix Matrix Multiplication

In [57]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [36]:
m.shape

(3, 4)

In [52]:
def matrix_matrix_multiplication(m,V):
    assert m.shape[1] == V.shape[0]
    num_rows = m.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows,num_cols))
    
    for i in range(num_cols):
        vi = V[:,i]
        resi = matrix_vector_multiplication(m,vi)
        result[:,i] = resi
    return result

In [53]:
matrix_matrix_multiplication(m,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
m.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [58]:
num_cols = V.shape[1]
for i in range(num_cols):
        vi = V[:,i]
        print(vi)
        resi = matrix_vector_multiplication(m,vi)
        print(resi)


[1. 0. 0. 2.]
[14.  5.  5.]
[1.  0.5 2.  1. ]
[20.   6.   8.5]
[2. 1. 1. 0.]
[13.  5.  9.]


## Identity Matrix

In [59]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

In [64]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [70]:
V[0:3,:]

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [71]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [72]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])