In [ ]:
import numpy as np

In [2]:
np

<module 'numpy' from '/opt/conda/lib/python3.11/site-packages/numpy/__init__.py'>

## creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(12,2.4)

array([2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4])

In [8]:
a= np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
a[2]

np.int64(3)

In [15]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.linspace(0,1,11)
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

## Multi-dimentional arrays

In [21]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
n[0,1] = 20

In [28]:
n[0]

array([ 1, 20,  3])

In [29]:
n[:,1]

array([20,  5,  8])

In [30]:
n[2] = [1,1,1]

In [31]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

## Randomly generated arrays

In [34]:
np.random.seed(10) ### fix the random numbers

np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [35]:
np.random.seed(2)

In [37]:
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [40]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [41]:
a+1

array([1, 2, 3, 4, 5])

In [43]:
a * 200 

array([  0, 200, 400, 600, 800])

In [46]:
b = (10 + (a*2))**2/100

In [47]:
a + b 

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [48]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

array([False, False, False, False, False])

## Comparison Operations

In [57]:
a

array([0, 1, 2, 3, 4])

In [50]:
a > b + 10

array([False, False, False, False, False])

In [51]:
a >=2

array([False, False,  True,  True,  True])

In [55]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [52]:
a > b

array([False, False,  True,  True,  True])

In [56]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [58]:
a.min()

np.int64(0)

In [59]:
a.max()

np.int64(4)

In [60]:
a.sum()

np.int64(10)

In [61]:
a.mean()

np.float64(2.0)

In [62]:
a.std()

np.float64(1.4142135623730951)